[package]
name = "iced-vmacro"
version = "0.1.0"
authors = ["cathiecode <cathiecode@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
iced = "0.2"
